name: .NET

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Riot
      run: dotnet bin/Debug/net5.0/LeagueOfItems.dll riot
      env:
        "Github:Token": ${{ secrets.Token }}
    - name: U.GG
      run: dotnet bin/Debug/net5.0/LeagueOfItems.dll ugg
      env:
        "Github:Token": ${{ secrets.Token }}
    - name: Github
      run: dotnet bin/Debug/net5.0/LeagueOfItems.dll github
      env:
        "Github:Token": ${{ secrets.Token }}
